#!/usr/local/bin/node --harmony
// Generated by LiveScript 1.3.1
(function(){
  var docopt, fs, shelljs, server, exec, getOptions, configureServerDependencies, configureCliDependencies, main;
  docopt = require('docopt').docopt;
  fs = require('fs');
  shelljs = require('shelljs');
  server = require('./lib/server');
  exec = require('bluebird').promisify(shelljs.exec);
  getOptions = function(){
    var doc, getOption, o, port, code, engine, dry;
    doc = shelljs.cat(__dirname + "/docs/usage.md");
    getOption = function(a, b, def, o){
      if (!o[a] && !o[b]) {
        return def;
      } else {
        return o[b];
      }
    };
    o = docopt(doc);
    port = getOption('-p', '--port', 1666, o);
    code = o['CODE'];
    engine = getOption('-e', '--engine', 'javascript', o);
    dry = getOption('-d', '--dry', false, o);
    if (o['run']) {
      return {
        serve: false,
        run: true,
        code: code,
        engine: engine,
        dry: dry
      };
    } else {
      return {
        serve: true,
        run: false,
        port: port
      };
    }
  };
  configureServerDependencies = function(){
    var configure;
    configure = require('./lib/das').configure;
    return configure({
      'fs': 'fs',
      'shelljs': 'shelljs',
      'os': 'os',
      'uid': 'uid'
    });
  };
  configureCliDependencies = function(isItDry){
    var configure, dryWrite, dryExec;
    configure = require('./lib/das').configure;
    dryWrite = function(name, content, mode, callback){
      console.log("Writing to " + name + ": " + content);
      return callback(null, 'ok');
    };
    dryExec = function(command, opts, callback){
      console.log("Executing: " + command);
      return callback(0, 'ok');
    };
    if (isItDry) {
      if (require('os').platform() !== 'darwin') {
        return configure({
          'fs': {
            writeFile: dryWrite
          },
          'shelljs': {
            exec: dryExec
          },
          'os': 'os',
          'uid': 'uid'
        });
      } else {
        return configure({
          'fs': {
            writeFile: dryWrite
          },
          'shelljs': {
            exec: dryExec
          },
          'os': {
            tmpdir: function(){
              return "faketmp";
            }
          },
          'uid': function(){
            return 'fakeuid';
          }
        });
      }
    } else {
      return configure({
        'fs': 'fs',
        'shelljs': 'shelljs',
        'os': 'os',
        'uid': 'uid'
      });
    }
  };
  main = function(){
    var ref$, serve, run, port, code, engine, dry;
    ref$ = getOptions(), serve = ref$.serve, run = ref$.run;
    if (serve) {
      port = getOptions().port;
      return server.bringup(port);
    } else {
      ref$ = getOptions(), code = ref$.code, engine = ref$.engine, dry = ref$.dry;
      configureCliDependencies(dry);
      return require('./lib/codejail').run(engine, code);
    }
  };
  main();
}).call(this);
