// Generated by LiveScript 1.3.1
(function(){
  var buildMocks, runTests, main;
  buildMocks = function(){
    var configure, mfs, mshelljs, mos, fakeuid;
    configure = require('./das').configure;
    mfs = {};
    mshelljs = {};
    mos = {};
    mfs.writeFile = function(name, content, mode, callback){
      console.log("Writing to " + name + ": " + content);
      return callback(null, 'ok');
    };
    mshelljs.exec = function(command, opts, callback){
      console.log("Executing: " + command);
      return callback(0, 'ok');
    };
    mos.tmpdir = function(){
      return "/fake/tmp";
    };
    fakeuid = function(){
      return "fakeuid";
    };
    return configure({
      'fs': mfs,
      'shelljs': mshelljs,
      'os': mos,
      'uid': fakeuid
    });
  };
  runTests = function(){
    var ref$, jail_code, run;
    ref$ = require('./codejail'), jail_code = ref$.jail_code, run = ref$.run;
    return jail_code("fake", "x+1", "p1", {
      f1: "f1",
      f2: "f2"
    }, "", "x1").then(function(){
      return run("fake", "x+y+z");
    }).then(function(it){
      return console.log(it);
    }, function(it){
      return console.log(it);
    });
  };
  main = function(){
    buildMocks();
    return runTests();
  };
  main();
}).call(this);
