// Generated by LiveScript 1.3.1
(function(){
  "use strict";
  var required, _module;
  required = require('./das').required;
  _module = function(_, moment, fs, $, __, co, debug, uid, os){
    return function(){
      var cmd, writeAsync, commands, tempDir, default_limits, setLimits, configure, jail_code, configureAll, simplyRun, iface;
      cmd = function(it){
        return $.promisify(__.exec)(it, {
          async: true
        });
      };
      writeAsync = $.promisify(fs.writeFile);
      commands = {};
      tempDir = os.tmpdir();
      default_limits = {
        cpu: 1,
        realtime: 1,
        fsize: 0
      };
      setLimits = function(it){
        return default_limits = _.assign(default_limits, it);
      };
      configure = function(command, binary_path, profile, user){
        return commands[command] = {
          cmdline_start: binary_path + "",
          user: user,
          profile: profile
        };
      };
      jail_code = function(engine, code, argv, files, stdin){
        return co(function*(){
          var command, sandboxDir, user, result, success, e;
          command = "";
          sandboxDir = tempDir + "/" + uid(8);
          yield cmd("mkdir -p " + sandboxDir);
          command = command + ("SANDBOXDIR=" + sandboxDir + " ");
          yield _.mapValues(files, function(content, name){
            return writeAsync(sandboxDir + "/" + name, content, 'utf-8');
          });
          yield writeAsync(sandboxDir + "/profile.aa", commands[engine].profile(sandboxDir + "/jailed.code"), 'utf-8');
          yield cmd("sudo apparmor_parser -a " + sandboxDir + "/profile.aa");
          code = ("#!" + commands[engine].cmdline_start + "\n") + code;
          yield writeAsync(sandboxDir + "/jailed.code", code, 'utf-8');
          yield cmd("chmod +x " + sandboxDir + "/jailed.code");
          user = commands[engine].user;
          if (user != null) {
            command = command + ("sudo -u " + user + " ");
          } else {
            command = command + "sudo ";
          }
          command = command + ("aa-exec -f " + sandboxDir + "/profile.aa " + sandboxDir + "/jailed.code");
          try {
            result = yield cmd(command);
            success = true;
          } catch (e$) {
            e = e$;
            result = e;
            success = false;
          }
          yield cmd("sudo apparmor_parser -R " + sandboxDir + "/profile.aa");
          yield cmd("rm -rf " + sandboxDir);
          return {
            success: success,
            result: result
          };
        })['catch'](function(){
          return {
            success: false,
            result: 'internal error'
          };
        });
      };
      configureAll = function(){
        var profiles, name, value, results$ = [];
        profiles = require('./profiles');
        for (name in profiles) {
          value = profiles[name];
          results$.push(configure(name, value.path, value.aa, value.user));
        }
        return results$;
      };
      simplyRun = function(engine, code){
        var profiles;
        configureAll('run-sandbox');
        profiles = require('./profiles');
        if (profiles[engine] == null) {
          throw "Sorry, no current profile for " + engine;
        }
        return jail_code(engine, code, "", {}, "");
      };
      iface = {
        configure: configure,
        jail_code: jail_code,
        run: simplyRun,
        configureAll: configureAll
      };
      return iface;
    };
  };
  module.exports = _module(require('lodash'), require('moment'), required()('fs'), require('bluebird'), required()('shelljs'), require('co'), require('debug')('codejail'), required()('uid'), required()('os'))();
}).call(this);
