// Generated by LiveScript 1.3.1
(function(){
  var debug, _module;
  debug = require('debug')('config');
  _module = function(){
    var config, iface;
    config = {};
    iface = {
      set: function(it){
        return config = it;
      },
      get: function(){
        return config;
      }
    };
    return iface;
  };
  module.exports = _module();
}).call(this);
