// Generated by LiveScript 1.3.1
(function(){
  "use strict";
  var debug, _module;
  debug = require('debug')('grader');
  _module = function(profiles){
    var sanitize, grade, iface;
    debug("Started");
    sanitize = function(response, payload){
      var ref$;
      if (response == null) {
        throw "Sorry, you should specify a response";
      }
      payload.context == null && (payload.context = "");
      return (ref$ = payload.validation) != null
        ? ref$
        : payload.validation = "";
    };
    grade = function(response, payload){
      var program, ref$, run;
      sanitize(response, payload);
      debug(payload);
      if (((ref$ = profiles[payload.lang]) != null ? ref$.code : void 8) != null) {
        program = profiles[payload.lang].code(response, payload);
      } else {
        program = "" + payload.context + "\n" + response + "\n" + payload.validation;
      }
      debug(program);
      run = require('./codejail').run;
      return run(payload.lang, program).then(function(it){
        var success, result;
        success = it.success, result = it.result;
        if (!success) {
          return {
            correct: false,
            score: 0,
            msg: "no! output: " + result,
            program: program
          };
        } else {
          return {
            correct: true,
            score: 1,
            msg: "ok! output: " + result,
            program: program
          };
        }
      });
    };
    iface = {
      grade: grade
    };
    return iface;
  };
  module.exports = _module(require('./profiles'));
}).call(this);
