// Generated by LiveScript 1.3.1
(function(){
  "use strict";
  var _module;
  _module = function(_, debug){
    var grade, iface;
    debug = debug('grader');
    grade = function*(response, payload){
      var graderApi;
      console.log(payload);
      if (payload.lang != null) {
        graderApi = require("./lang/" + payload.lang);
        return graderApi.grade(response, payload);
      } else {
        throw "Sorry, " + payload.lang + " is invalid";
      }
    };
    iface = {
      grade: grade
    };
    return iface;
  };
  module.exports = _module(require("lodash"), require("debug"));
}).call(this);
