// Generated by LiveScript 1.3.1
(function(){
  var debug, _module;
  debug = require('debug')('profiles');
  _module = function(){
    var iface;
    iface = {
      'node': {
        path: "/usr/local/bin/node",
        user: "node-sandbox",
        aa: "#include <tunables/global>\n\nnodeScriptProfile {\n    #include <abstractions/base>\n}"
      },
      'mnode': {
        path: "/usr/local/bin/node",
        aa: "#include <tunables/global>\n\nnodeScriptProfile {\n    #include <abstractions/base>\n}"
      },
      'octave': {
        path: "path/to/octave",
        aa: "this is the octave profile "
      }
    };
    return iface;
  };
  module.exports = _module();
}).call(this);
