// Generated by LiveScript 1.3.1
(function(){
  var debug, os, _module;
  debug = require('debug')('profiles');
  os = require('os');
  _module = function(){
    var iface;
    iface = {
      'javascript': {
        path: "/usr/local/bin/node",
        aa: function(it){
          return "#include <tunables/global>\n\n" + it + " {\n    #include <abstractions/base>\n    /usr/local/bin/node mr,\n    " + it + " mr,\n}";
        }
      },
      'octave': {
        path: "/Users/zaccaria/development/github/gitbook2edx-octave-helper/bin/octave-helper",
        aa: function(it){
          return "#include <tunables/global>\n\n" + it + " {\n    #include <abstractions/base>\n    /usr/local/bin/octave mr,\n    /usr/bin/octave mr,\n    " + it + " mr,\n}";
        }
      },
      'fake': {
        path: "/bin/cat",
        aa: function(){
          return "";
        }
      }
    };
    return iface;
  };
  module.exports = _module();
}).call(this);
