// Generated by LiveScript 1.3.1
(function(){
  var request, create, expect, b64, app, $, packet, testPayload, testPayloadFail;
  request = require('co-supertest');
  create = require('./server').create;
  expect = require('chai').expect;
  b64 = require('base64-url');
  app = create();
  request = request.agent(app.listen());
  $ = function(it){
    return JSON.stringify(it(), 0, 4);
  };
  packet = function(studentId, response, payload){
    return {
      xqueue_body: $(function(){
        return {
          student_info: $(function(){
            return {
              anonymized_id: studentId
            };
          }),
          student_response: response,
          grader_payload: $(function(){
            return {
              payload: b64.encode($(function(){
                return payload;
              }))
            };
          })
        };
      })
    };
  };
  testPayload = {
    lang: 'fakelang',
    base: "original-text",
    solution: "original-solution",
    validation: "assert(x==1);",
    context: null
  };
  testPayloadFail = {
    lang: 'fakelang',
    base: "original-text",
    solution: "original-solution",
    validation: "bombit",
    context: null
  };
  describe('Initialization', function(empty){
    it('should return 404 when method is not post', function*(){
      var res;
      res = yield request.get('/').expect(404).end();
      expect(res.text).to.equal('sorry, only POST methods allowed');
    });
    it('should return an error when the request is not compliant with specs', function*(){
      var res;
      res = yield request.post('/').send({
        foo: true
      }).expect(406).end();
    });
    it('should return a success when request is compliant', function*(){
      var res, val;
      res = yield request.post('/').send(packet(333, 'var x = 1;', testPayload)).expect(200).end();
      val = JSON.parse(res.text);
      expect(val.correct).to.equal(true);
    });
    return it('should return a fail when program fails', function*(){
      var res, val;
      res = yield request.post('/').send(packet(333, 'var x = 1;', testPayloadFail)).expect(200).end();
      val = JSON.parse(res.text);
      expect(val.msg).to.equal("noo! it failed");
    });
  });
}).call(this);
