// Generated by LiveScript 1.3.1
(function(){
  var ref$, configure, jail_code, run, configureAll;
  ref$ = require('./codejail').mocked, configure = ref$.configure, jail_code = ref$.jail_code, run = ref$.run, configureAll = ref$.configureAll;
  configureAll('sandbox');
  jail_code("node", "x+1", "p1", {
    f1: "f1",
    f2: "f2"
  }, "", "x1").then(function(){
    return run("node", "x+y+z");
  }).then(function(it){
    return console.log(it);
  }, function(it){
    return console.log(it);
  });
}).call(this);
