// Generated by LiveScript 1.3.1
(function(){
  var request, create, expect, b64, app, $, packet, configureServerDependencies, fakeTestPayload, fakeTestPayloadFail, rq, rqfail;
  request = require('co-supertest');
  create = require('../server').create;
  expect = require('chai').expect;
  b64 = require('base64-url');
  app = create();
  request = request.agent(app.listen());
  $ = function(it){
    return JSON.stringify(it(), 0, 4);
  };
  packet = function(studentId, response, payload){
    return {
      xqueue_body: $(function(){
        return {
          student_info: $(function(){
            return {
              anonymized_id: studentId
            };
          }),
          student_response: response,
          grader_payload: $(function(){
            return {
              payload: b64.encode($(function(){
                return payload;
              }))
            };
          })
        };
      })
    };
  };
  configureServerDependencies = function(){
    var configure;
    configure = require('../das').configure;
    return configure({
      'fs': 'fs',
      'shelljs': 'shelljs',
      'os': 'os',
      'uid': 'uid'
    });
  };
  configureServerDependencies();
  fakeTestPayload = {
    lang: 'fake',
    base: "original-text",
    solution: "original-solution",
    validation: "assert(x==1);",
    context: null
  };
  fakeTestPayloadFail = {
    lang: 'fake',
    base: "original-text",
    solution: "original-solution",
    validation: "bombit",
    context: null
  };
  rq = function(it){
    return request.post('/').send(it).set('Accept', 'application/json').expect('Content-Type', /json/).expect(200).end();
  };
  rqfail = function(it){
    return request.post('/').send(it).set('Accept', 'application/json').expect('Content-Type', /json/).expect(406).end();
  };
  describe('#server', function(empty){
    describe('Basic request/response protocol', function(empty){
      it('should return 404 when method is not post', function*(){
        var res;
        res = yield request.get('/').expect(404).end();
        expect(res.text).to.equal('sorry, only POST methods allowed');
      });
      return it('should return an error when the request is not compliant with specs', function*(){
        var res;
        res = yield request.post('/').send({
          foo: true
        }).expect(406).end();
      });
    });
    describe('Compliant requests', function(empty){
      it('should succeed when fake program works', function*(){
        var res;
        res = yield rq(packet(333, 'var x = 1;', fakeTestPayload));
        expect(res.body.correct).to.equal(true);
      });
      return it('should not run a program without a language id', function*(){
        var res;
        res = yield rqfail(packet(333, 'var x=1; console.log(x);', {
          validation: ""
        }));
      });
    });
    describe('Javascript execution', function(empty){
      var o, jsTests, i$, len$, t, results$ = [];
      o = function(program, validation, correct, msg, desc){
        var actions;
        actions = function*(){
          var res;
          res = yield rq(packet(333, program, {
            lang: 'javascript',
            validation: validation
          }));
          expect(res.body.msg).to.equal(msg);
          expect(res.body.correct).to.equal(correct);
        };
        if (correct) {
          return {
            desc: "when: " + desc + " -> it should work",
            actions: actions
          };
        } else {
          return {
            desc: "when: " + desc + " -> it should not work",
            actions: actions
          };
        }
      };
      jsTests = [o('var x=1; console.log(x);', '', true, "ok! output: 1\n", 'working program, empty validation     '), o('var x=1; console.log(x);', undefined, true, "ok! output: 1\n", 'working program, undefined validation '), o('var x=1; console.log(x);', 'return 0', true, "ok! output: 1\n", 'working program, safe validation      '), o('var x=1; console.log(x);', 'process.exit(0)', true, "ok! output: 1\n", 'working program, safe validation      '), o('var x=1; console.log(x);', 'process.exit(2)', false, "no! output: Error: 2", 'working program, returns error        '), o('var x=1; console.log(x);', "require('assert')(x==1); process.exit(0)", true, "ok! output: 1\n", 'working program, validation succ      '), o('var x=1; console.log(x);', "require('assert')(x==2); process.exit(0)", false, "no! output: Error: 1", 'working program, validation fails     ')];
      for (i$ = 0, len$ = jsTests.length; i$ < len$; ++i$) {
        t = jsTests[i$];
        results$.push(it(t.desc, t.actions));
      }
      return results$;
    });
    return describe('Octave execution', function(empty){
      var o, octaveTests, i$, len$, t, results$ = [];
      o = function(program, validation, correct, msg, desc){
        var actions;
        actions = function*(){
          var res;
          res = yield rq(packet(333, program, {
            lang: 'octave',
            validation: validation
          }));
          expect(res.body.msg).to.equal(msg);
          expect(res.body.correct).to.equal(correct);
        };
        if (correct) {
          return {
            desc: "when: " + desc + " -> it should work",
            actions: actions
          };
        } else {
          return {
            desc: "when: " + desc + " -> it should not work",
            actions: actions
          };
        }
      };
      octaveTests = [o('x=1+1', '', true, "ok! output: x =  2\n\n", 'working program, empty validation     '), o('x=sin(1)', 'exit(0);\n', true, "ok! output: x =  0.84147\n\n\n", 'working program, safe validation      '), o('x=1;', 'exit(2);\n', false, "no! output: Error: 1", 'working program, returns error        '), o('x=1', "assert(x==1)\nexit(0)", true, "ok! output: x =  1\n\n\n", 'working program, validation succ      '), o('x=1', "assert(x==2)\nexit(0)", false, "no! output: Error: 1", 'working program, validation fails     ')];
      for (i$ = 0, len$ = octaveTests.length; i$ < len$; ++i$) {
        t = octaveTests[i$];
        results$.push(it(t.desc, t.actions));
      }
      return results$;
    });
  });
}).call(this);
