// Generated by LiveScript 1.3.1
(function(){
  var _, moment, fs, $, __, debug, exec, _module;
  _ = require('lodash');
  moment = require('moment');
  fs = require('fs');
  $ = require('bluebird');
  __ = require('shelljs');
  debug = require('debug')('fakelang');
  exec = $.promisify(__.exec);
  _module = function(){
    var grade, iface;
    grade = function(response, payload){
      var program, result, e;
      payload.context == null && (payload.context = "");
      payload.valudation == null && (payload.valudation = "");
      program = "" + payload.context + "\n" + response + "\n" + payload.validation;
      try {
        if (payload.validation === "bombit") {
          throw "Ouch!";
        }
        result = program;
      } catch (e$) {
        e = e$;
        return {
          correct: false,
          score: 0,
          msg: "noo! it failed"
        };
      }
      return {
        correct: true,
        score: 1,
        msg: program
      };
    };
    iface = {
      grade: grade
    };
    return iface;
  };
  module.exports = _module();
}).call(this);
