// Generated by LiveScript 1.3.1
(function(){
  var debug, required, run, _module;
  debug = require('debug')('javascript');
  required = require('../das').required;
  run = require('../codejail').run;
  _module = function(){
    var sanitize, grade, iface;
    sanitize = function(response, payload){
      var ref$;
      if (response == null) {
        throw "Sorry, you should specify a response";
      }
      payload.context == null && (payload.context = "");
      return (ref$ = payload.valudation) != null
        ? ref$
        : payload.valudation = "";
    };
    grade = function(response, payload){
      var program;
      sanitize(response, payload);
      program = "" + payload.context + "\n" + response + "\n" + payload.validation;
      return run('mnode', program).then(function(it){
        var success, result;
        success = it.success, result = it.result;
        if (!success) {
          return {
            correct: false,
            score: 0,
            msg: "no! output: " + result,
            program: program
          };
        } else {
          return {
            correct: true,
            score: 1,
            msg: "ok! output: " + result,
            program: program
          };
        }
      });
    };
    iface = {
      grade: grade
    };
    return iface;
  };
  module.exports = _module();
}).call(this);
